manifest:
  
  defaults:
    remote: alif

  remotes:
    - name: alif
      url-base: gitAlif:alifsemi
  
  projects:
    - name: zephyr
      repo-path: zephyr_alif
      revision: zas-v2.x-dev
      import: true

  self:
    path: .
