manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/AlifSemi-Sirin
  projects:
    - name: zephyr_alif_fork_4.1
      remote: zephyrproject-rtos
      revision: zas-v2.x-dev-mr
      path: zephyr
      import: true
  self:
    path: .
